# Assignment 2: Lecture 4, 5, 6

In [1]:
import numpy as np
import pandas as pd

records = [
{"order_id": 101, "date": "2026-01-03", "customer": "Ava", "city": "Boston", "category": "Books", "units": 2, "unit_price": 12.50},
{"order_id": 102, "date": "2026-01-03", "customer": "Noah", "city": "Boston", "category": "Games", "units": 1, "unit_price": 59.99},
{"order_id": 103, "date": "2026-01-04", "customer": "Ava", "city": "Seattle", "category": "Books", "units": 3, "unit_price": 12.50},
{"order_id": 104, "date": "2026-01-05", "customer": "Mia", "city": "Seattle", "category": "Garden", "units": 4, "unit_price": 7.25},
{"order_id": 105, "date": "2026-01-06", "customer": "Liam", "city": "Austin", "category": "Books", "units": 1, "unit_price": 20.00},
{"order_id": 106, "date": "2026-01-06", "customer": "Noah", "city": "Austin", "category": "Garden", "units": 2, "unit_price": 7.25},
{"order_id": 107, "date": "2026-01-07", "customer": "Mia", "city": "Boston", "category": "Games", "units": 2, "unit_price": 59.99},
{"order_id": 108, "date": "2026-01-08", "customer": "Ava", "city": "Austin", "category": "Books", "units": 2, "unit_price": 12.50},
]

df = pd.DataFrame(records)

## Part A: NumPy 

1. Problem 1:

In [4]:
a=np.arange(0,20)
print(a)
b=np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19]])
print(b)
c=np.array(b/3)
print(c)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[0.         0.33333333 0.66666667 1.         1.33333333]
 [1.66666667 2.         2.33333333 2.66666667 3.        ]
 [3.33333333 3.66666667 4.         4.33333333 4.66666667]
 [5.         5.33333333 5.66666667 6.         6.33333333]]


The shape of array a is 1D, and the shapes of arrays b and c are 2D. The dtypes of array a and b is integer, and the dtype for c is float. C has a float as it's dtype because it has partial values such as 0.33.

2.Problem 2

In [9]:
b[:3]
print(b[:,3])

b[2:,[2,3,4]]
print(b[2:,2:,4:,])

[ 3  8 13 18]


IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed